### ISSUE TITLE
null length crash

### ISSUE THREAD

**Issue by shokk** [chriszelazo/homebridge-switcheroo#2]
What could be causing this? This is the error I get running Homebridge with the homebridge-switcheroo plugin

[5/8/2017, 10:54:31 AM] [OfficeSonos Playlist] [Multiswitch]: OfficeSonos Playlist
[5/8/2017, 10:54:31 AM] [OfficeSonos Playlist] ---+--- Chili Peppers
[5/8/2017, 10:54:31 AM] [OfficeSonos Playlist]    |--- A Perfect Circle
[5/8/2017, 10:54:31 AM] [OfficeSonos Playlist]    |--- Korn
[5/8/2017, 10:54:31 AM] [OfficeSonos Playlist]    |--- Serj
[5/8/2017, 10:54:31 AM] [OfficeSonos Playlist]    +--- Ozzy
/usr/local/lib/node_modules/homebridge/lib/server.js:358
      for (var i = 0; i < foundAccessories.length; i++) {
                                          ^

TypeError: Cannot read property 'length' of null
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:358:43)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:15:19
    at /usr/local/lib/node_modules/homebridge-directv/index.js:58:5
    at /usr/local/lib/node_modules/homebridge-directv/node_modules/directv-remote/index.js:262:21
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-directv/node_modules/directv-remote/index.js:314:13)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at Socket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)

This is my code...
   "accessories":[
        {   
            "accessory": "Switcheroo",
            "type": "multiswitch",
            "name": "OfficeSonos Playlist",
            "host": "http://10.0.1.202:5005/OfficeSonos/musicsearch",
            "multiswitch": [
                { "name": "Chili Peppers", "path": "/apple/song/Red+Hot+Chili+Peppers" },
                { "name": "A Perfect Circle", "path": "/apple/song/A+Perfect+Circle" },
                { "name": "Korn", "path": "/apple/song/Korn" },
                { "name": "Serj", "path": "/apple/song/Serj+Tankian" },
                { "name": "Ozzy", "path": "/apple/song/Ozzy+Osbourne" }
            ]
        }
    ]

**Comment by webbrain-one** [comment]
Hey @chrszlz, I opened a PR to fix this: https://github.com/chrszlz/homebridge-switcheroo/pull/10. It should prevent the `Cannot read property 'length' of null` crash by making sure the plugin returns a valid accessories array instead of `null`, so Homebridge can safely start up. Would you mind testing it and letting me know if it resolves the issue for you?
